/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.EstudianteJDBC;
import Domain.AtributosEstudiante;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres R
 */
public class VentanaEstudiante extends javax.swing.JFrame {

    EstudianteJDBC dbestudiante = new EstudianteJDBC();
    public VentanaEstudiante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_BuscarEstudiante = new javax.swing.JTextField();
        cbx_buscarestudiante = new javax.swing.JComboBox<>();
        btn_MostrarEstudiantes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Lector", "CC", "Nombre", "Apellido", "Direccion", "Carrera", "Fecha_Nac", "Telefono", "Email", "Password", "Id_EstadoEstudiante"
            }
        ));
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(204, 0, 0));
        rSTableMetro1.setColorFilasForeground1(new java.awt.Color(204, 0, 0));
        rSTableMetro1.setColorFilasForeground2(new java.awt.Color(204, 0, 0));
        rSTableMetro1.setColorSelBackgound(new java.awt.Color(204, 0, 0));
        rSTableMetro1.setRowHeight(30);
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rSTableMetro1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 990, 500));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setText("Buscar Estudiante");

        cbx_buscarestudiante.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        cbx_buscarestudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar Por ID", "Buscar Por CC", "Buscar Por NOMBRE", "Buscar Por EMAIL" }));
        cbx_buscarestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_buscarestudianteActionPerformed(evt);
            }
        });

        btn_MostrarEstudiantes.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btn_MostrarEstudiantes.setText("Mostrar Estudiantes");
        btn_MostrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(txt_BuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_buscarestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_MostrarEstudiantes)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_BuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_buscarestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MostrarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 990, 50));

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel3.setText("GESTION DE ESTUDIANTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel4.setText("REGRESAR");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FondoVentanaEstudiante.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_buscarestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_buscarestudianteActionPerformed
        String c1 = (String) cbx_buscarestudiante.getSelectedItem();
        if (c1.equals("Buscar Por ID")) {
            LimpiarDatos();
            BuscarPorId();
        } else if (c1.equals("Buscar Por CC")) {
            LimpiarDatos();
            BuscarPorCC();
        } else if (c1.equals("Buscar Por NOMBRE")) {
            LimpiarDatos();
            BuscarPorNombre();
        } else if (c1.equals("Buscar Por EMAIL")) {
            LimpiarDatos();
            BuscarPorEmail();
        }    
    }//GEN-LAST:event_cbx_buscarestudianteActionPerformed

    private void btn_MostrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarEstudiantesActionPerformed
        LimpiarDatos();
        SelectEstudiantes(); 
    }//GEN-LAST:event_btn_MostrarEstudiantesActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        VentanaEditarUsuario ventana = new VentanaEditarUsuario();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        try {
            int selectedRowIndex = rSTableMetro1.getSelectedRow();
            ventana.txt_eid_Lector.setText(tb.getValueAt(selectedRowIndex, 0).toString());
            ventana.txt_CC.setText(tb.getValueAt(selectedRowIndex, 1).toString());
            ventana.txt_nombre.setText(tb.getValueAt(selectedRowIndex, 2).toString());
            ventana.txt_apellido.setText(tb.getValueAt(selectedRowIndex, 3).toString());
            ventana.txt_eDireccion.setText(tb.getValueAt(selectedRowIndex, 4).toString());
            ventana.txt_carrera.setText(tb.getValueAt(selectedRowIndex, 5).toString());
            ventana.txt_fecha_nac.setText(tb.getValueAt(selectedRowIndex, 6).toString());
            ventana.txt_eTelefono.setText(tb.getValueAt(selectedRowIndex, 7).toString());
            ventana.txt_Email.setText(tb.getValueAt(selectedRowIndex, 8).toString());
            ventana.txt_ePassword.setText(tb.getValueAt(selectedRowIndex, 9).toString());
            ventana.txt_eEstado.setText(tb.getValueAt(selectedRowIndex, 10).toString());
            this.dispose();
            ventana.setVisible(true);

        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println(e);
            ventana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel4MouseClicked
 
    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked
   
        
         
    }//GEN-LAST:event_rSTableMetro1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstudiante().setVisible(true);
            }
        });
    }
    public void SelectEstudiantes(){
        List<AtributosEstudiante> Estudiante;
        Estudiante = dbestudiante.select();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (AtributosEstudiante in : Estudiante) {
            tb.addRow(new Object[]{in.getId_Lector(), in.getCI(), in.getNombre(), in.getApellido(), in.getDireccion(), in.getCarrera(), in.getFecha_Nac(), in.getTelefono(), in.getEmail(), in.getPassword(), in.getId_EstadoEstudiante()});
        }  
    }
    public void LimpiarDatos() {
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }
    }
    public void BuscarPorId(){
        List<AtributosEstudiante> Estudiante;
        String param2 = txt_BuscarEstudiante.getText();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        String param1 = "Id_Lector";
            Estudiante = dbestudiante.BuscarEstudiante(param1, param2);
            for (AtributosEstudiante in : Estudiante) {
                tb.addRow(new Object[]{in.getId_Lector(), in.getCI(), in.getNombre(), in.getApellido(), in.getDireccion(), in.getCarrera(), in.getFecha_Nac(), in.getTelefono(), in.getEmail(), in.getPassword(), in.getId_EstadoEstudiante()});
            }
    }
    public void BuscarPorCC(){
        List<AtributosEstudiante> Estudiante;
        String param2 = txt_BuscarEstudiante.getText();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        String param1 = "CC";
            Estudiante = dbestudiante.BuscarEstudiante(param1, param2);
            for (AtributosEstudiante in : Estudiante) {
                tb.addRow(new Object[]{in.getId_Lector(), in.getCI(), in.getNombre(), in.getApellido(), in.getDireccion(), in.getCarrera(), in.getFecha_Nac(), in.getTelefono(), in.getEmail(), in.getPassword(), in.getId_EstadoEstudiante()});
            }
    }
    public void BuscarPorNombre(){
        List<AtributosEstudiante> Estudiante;
        String param2 = txt_BuscarEstudiante.getText();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        String param1 = "nombre";
            Estudiante = dbestudiante.BuscarEstudiante(param1, param2);
            for (AtributosEstudiante in : Estudiante) {
                tb.addRow(new Object[]{in.getId_Lector(), in.getCI(), in.getNombre(), in.getApellido(), in.getDireccion(), in.getCarrera(), in.getFecha_Nac(), in.getTelefono(), in.getEmail(), in.getPassword(), in.getId_EstadoEstudiante()});
            }
    }
    public void BuscarPorEmail(){
        List<AtributosEstudiante> Estudiante;
        String param2 = txt_BuscarEstudiante.getText();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        String param1 = "email";
            Estudiante = dbestudiante.BuscarEstudiante(param1, param2);
            for (AtributosEstudiante in : Estudiante) {
                tb.addRow(new Object[]{in.getId_Lector(), in.getCI(), in.getNombre(), in.getApellido(), in.getDireccion(), in.getCarrera(), in.getFecha_Nac(), in.getTelefono(), in.getEmail(), in.getPassword(), in.getId_EstadoEstudiante()});
            }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MostrarEstudiantes;
    private javax.swing.JComboBox<String> cbx_buscarestudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro rSTableMetro1;
    private javax.swing.JTextField txt_BuscarEstudiante;
    // End of variables declaration//GEN-END:variables
}
