/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.VistaReservaUsuarioJDBC;
import Domain.AtributosVistaReservaUsuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres R
 */
public class VentanaLibrosReservados extends javax.swing.JFrame {

    VistaReservaUsuarioJDBC dbVistaReserva = new VistaReservaUsuarioJDBC();

    public VentanaLibrosReservados() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        labelnombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        lista_estadoPrestamo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_cc = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_apellido = new javax.swing.JLabel();
        label_direccion = new javax.swing.JLabel();
        label_carrera = new javax.swing.JLabel();
        label_fechanac = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("MIS LIBROS RESERVADOS");

        labelid.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        labelid.setText("jLabel4");

        labelnombre.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(labelid)
                .addGap(32, 32, 32)
                .addComponent(labelnombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnombre)
                    .addComponent(labelid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 320, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Reserva", "Id_Lector", "Nombre", "Apellido", "Titulo", "Fecha_Prestamo", "Fecha_Devuelo", "EstadoPrestamo"
            }
        ));
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        rSTableMetro1.setColorFilasForeground1(new java.awt.Color(0, 102, 102));
        rSTableMetro1.setColorFilasForeground2(new java.awt.Color(0, 102, 102));
        rSTableMetro1.setColorSelBackgound(new java.awt.Color(0, 102, 102));
        rSTableMetro1.setRowHeight(30);
        jScrollPane1.setViewportView(rSTableMetro1);

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel3.setText("Estado Del Prestamo:");

        lista_estadoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Prestamo", "Devuelto" }));
        lista_estadoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_estadoPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lista_estadoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lista_estadoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 760, 380));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FondoPrincipalUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        label_cc.setText("CC");
        jPanel1.add(label_cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        label_nombre.setText("NOMBRE");
        jPanel1.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        label_apellido.setText("APELLIDO");
        jPanel1.add(label_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        label_direccion.setText("DIRECCION ");
        jPanel1.add(label_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        label_carrera.setText("CARRERA");
        jPanel1.add(label_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        label_fechanac.setText("FECHA_NAC");
        jPanel1.add(label_fechanac, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        label_telefono.setText("TELEFONO");
        jPanel1.add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        label_email.setText("EMAIL");
        jPanel1.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lista_estadoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_estadoPrestamoActionPerformed
        String c1 = (String) lista_estadoPrestamo.getSelectedItem();
        if (c1.equals("Pendiente")) {
            LimpiarDatos();
            BuscarPorPendiente();
        } else if (c1.equals("En Prestamo")) {
            LimpiarDatos();
            BuscarPorEn_Prestamo();
        } else if (c1.equals("Devuelto")) {
            LimpiarDatos();
            BuscarPorDevuelto();
        }
    }//GEN-LAST:event_lista_estadoPrestamoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipalUsuario ventana = new VentanaPrincipalUsuario();
        
        ventana.label_name.setText(labelnombre.getText());
        ventana.label_Id_Lector.setText(labelid.getText());
        ventana.label_cc.setText(this.label_cc.getText());
        ventana.label_nombre.setText(this.label_nombre.getText());
        ventana.label_apellido.setText(this.label_apellido.getText());
        ventana.label_direccion.setText(this.label_direccion.getText());
        ventana.label_carrera.setText(this.label_carrera.getText());
        ventana.label_fechanac.setText(this.label_fechanac.getText());
        ventana.label_telefono.setText(this.label_telefono.getText());
        ventana.label_email.setText(this.label_email.getText());
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLibrosReservados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLibrosReservados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLibrosReservados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLibrosReservados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLibrosReservados().setVisible(true);
            }
        });
    }

    public void BuscarPorPendiente() {
        int Id_Lector = Integer.parseInt(labelid.getText());
        String Estado = "Pendiente";
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        List<AtributosVistaReservaUsuario> EstadoLibro;
        EstadoLibro = dbVistaReserva.select(Id_Lector, Estado);
        for (AtributosVistaReservaUsuario in : EstadoLibro) {
            tb.addRow(new Object[]{in.getId_Reserva(), in.getId_Lector(), in.getNombre(), in.getApellido(), in.getTitulo(), in.getFecha_Prestamo(), in.getFecha_Devuelto(), in.getEstadoPrestamo()});
        }
    }

    public void BuscarPorEn_Prestamo() {
        int Id_Lector = Integer.parseInt(labelid.getText());
        String Estado = "En Prestamo";
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        List<AtributosVistaReservaUsuario> EstadoLibro;
        EstadoLibro = dbVistaReserva.select(Id_Lector, Estado);
        for (AtributosVistaReservaUsuario in : EstadoLibro) {
            tb.addRow(new Object[]{in.getId_Reserva(), in.getId_Lector(), in.getNombre(), in.getApellido(), in.getTitulo(), in.getFecha_Prestamo(), in.getFecha_Devuelto(), in.getEstadoPrestamo()});
        }
    }

    public void BuscarPorDevuelto() {
        int Id_Lector = Integer.parseInt(labelid.getText());
        String Estado = "Devuelto";
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        List<AtributosVistaReservaUsuario> EstadoLibro;
        EstadoLibro = dbVistaReserva.select(Id_Lector, Estado);
        for (AtributosVistaReservaUsuario in : EstadoLibro) {
            tb.addRow(new Object[]{in.getId_Reserva(), in.getId_Lector(), in.getNombre(), in.getApellido(), in.getTitulo(), in.getFecha_Prestamo(), in.getFecha_Devuelto(), in.getEstadoPrestamo()});
        }
    }

    public void LimpiarDatos() {
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel label_apellido;
    public javax.swing.JLabel label_carrera;
    public javax.swing.JLabel label_cc;
    public javax.swing.JLabel label_direccion;
    public javax.swing.JLabel label_email;
    public javax.swing.JLabel label_fechanac;
    public javax.swing.JLabel label_nombre;
    public javax.swing.JLabel label_telefono;
    public javax.swing.JLabel labelid;
    public javax.swing.JLabel labelnombre;
    private javax.swing.JComboBox<String> lista_estadoPrestamo;
    private rojerusan.RSTableMetro rSTableMetro1;
    // End of variables declaration//GEN-END:variables
}
