/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Datos.PrestamoJDBC;
import Domain.Atributos;
import Domain.AtributosPrestamo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class VentanaValidarPrestamo extends javax.swing.JFrame {
    List<AtributosPrestamo> prestamos;
    PrestamoJDBC dbprestamo = new PrestamoJDBC();
    public String user;
    
    
    public VentanaValidarPrestamo() {
        initComponents();
        setLocationRelativeTo(null);
        txt_N_Prestamo.setEditable(false);
        txt_Id_Reserva.setEditable(false);
        txt_Fecha_Prestamo.setEditable(false);
        txt_Fecha_Devuelto.setEditable(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSliderBeanInfo1 = new rojeru_san.RSPanelsSliderBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_Mostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_N_Prestamo = new javax.swing.JTextField();
        txt_Id_Reserva = new javax.swing.JTextField();
        lista_validar = new javax.swing.JComboBox<>();
        txt_Fecha_Prestamo = new javax.swing.JTextField();
        txt_Fecha_Devuelto = new javax.swing.JTextField();
        btn_ValidarPrestamo = new javax.swing.JButton();
        lbl_usr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        btn_Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 266));

        btn_Mostrar.setFont(new java.awt.Font("Roboto Condensed", 1, 11)); // NOI18N
        btn_Mostrar.setText("Mostrar Prestamos");
        btn_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("VALIDAR PRESTAMO");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel3.setText("N_Prestamo:");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel4.setText("Id_Reserva:");

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel5.setText("Fecha_Prestamo:");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setText("Fecha_Devuelto:");

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel7.setText("Validado:");

        lista_validar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        lista_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_validarActionPerformed(evt);
            }
        });

        btn_ValidarPrestamo.setFont(new java.awt.Font("Roboto Condensed", 1, 11)); // NOI18N
        btn_ValidarPrestamo.setText("Validar Prestamo");
        btn_ValidarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ValidarPrestamoActionPerformed(evt);
            }
        });

        lbl_usr.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Id_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_N_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_Fecha_Devuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_Fecha_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_ValidarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lista_validar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_usr)
                        .addGap(104, 104, 104))))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_N_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Id_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Fecha_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_ValidarPrestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Fecha_Devuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lista_validar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 500, 266));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N_Prestamo", "Id_Reserva", "Id_Lector", "Nombre", "Apellido", "NombreLibro", "Fecha_Prestamo", "Fecha_Devuelto", "Validado"
            }
        ));
        rSTableMetro1.setRowHeight(30);
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rSTableMetro1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, 270));

        btn_Regresar.setFont(new java.awt.Font("Open Sans", 1, 11)); // NOI18N
        btn_Regresar.setText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FondoVentanaEditarUsuario.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarActionPerformed
        LimpiarDatos();
        SelectPrestamos();
    }//GEN-LAST:event_btn_MostrarActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        String usuario = lbl_usr.getText();
        if(usuario.equals("root")){
            VentanaPrincipal ventana = new VentanaPrincipal();
            ventana.setVisible(true);
            ventana.label_nombre.setText(usuario);
            this.dispose();
        }
        else{
            VentanaPrincipalBibliotecologo ventana = new VentanaPrincipalBibliotecologo();
            ventana.setVisible(true);
            ventana.label_usuario.setText(usuario);
            this.dispose();
        }
    }//GEN-LAST:event_btn_RegresarActionPerformed
 
 
    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked
         DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
         int selectedRowIndex = rSTableMetro1.getSelectedRow();
         txt_N_Prestamo.setText(tb.getValueAt(selectedRowIndex, 0).toString());
         txt_Id_Reserva.setText(tb.getValueAt(selectedRowIndex, 1).toString());
         txt_Fecha_Prestamo.setText(tb.getValueAt(selectedRowIndex, 6).toString());
         txt_Fecha_Devuelto.setText(tb.getValueAt(selectedRowIndex, 7).toString());
    }//GEN-LAST:event_rSTableMetro1MouseClicked

    private void btn_ValidarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ValidarPrestamoActionPerformed
        int N_Prestamo = Integer.parseInt(txt_N_Prestamo.getText());
        String validar = "SI";
        dbprestamo.update(validar, N_Prestamo);
        if(dbprestamo.correcto){
            JOptionPane.showMessageDialog(null,"Se ha validado el Prestamo");
        }
        else{
            JOptionPane.showMessageDialog(null,"Ha ocurrido un error al validar el Prestamo");
        }
    }//GEN-LAST:event_btn_ValidarPrestamoActionPerformed

    private void lista_validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_validarActionPerformed
        String c1 = (String) lista_validar.getSelectedItem();
        if (c1.equals("SI")) {
            txt_N_Prestamo.setText("");
            txt_Id_Reserva.setText("");
            txt_Fecha_Prestamo.setText("");
            txt_Fecha_Devuelto.setText("");
            btn_ValidarPrestamo.setVisible(false);
            LimpiarDatos();
            SelectPrestamos();
        }
        else{
            txt_N_Prestamo.setText("");
            txt_Id_Reserva.setText("");
            txt_Fecha_Prestamo.setText("");
            txt_Fecha_Devuelto.setText("");
            btn_ValidarPrestamo.setVisible(true);
            LimpiarDatos();
            SelectPrestamos2();
        }
    }//GEN-LAST:event_lista_validarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaValidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaValidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaValidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaValidarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaValidarPrestamo().setVisible(true);
            }
        });
    }
    public void SelectPrestamos(){
        String validar = (String) lista_validar.getSelectedItem();
        prestamos = dbprestamo.select(validar);
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (AtributosPrestamo in : prestamos) {
            tb.addRow(new Object[]{in.getN_Prestamo(), in.getId_Reserva(), in.getId_Lector(), in.getNombre(), in.getApellido(), in.getNombreLibro(), in.getFecha_Prestamo(),in.getFecha_Devuelto(),in.getValidado()});
        }    
    }
    public void SelectPrestamos2(){
        String validar = (String) lista_validar.getSelectedItem();
        prestamos = dbprestamo.select(validar);
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (AtributosPrestamo in : prestamos) {
            tb.addRow(new Object[]{in.getN_Prestamo(), in.getId_Reserva(), in.getId_Lector(), in.getNombre(), in.getApellido(), in.getNombreLibro(), in.getFecha_Prestamo(),in.getFecha_Devuelto(),in.getValidado()});
        }   
    
    }
    public void LimpiarDatos() {
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Mostrar;
    public javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_ValidarPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lbl_usr;
    public javax.swing.JComboBox<String> lista_validar;
    private rojeru_san.RSPanelsSliderBeanInfo rSPanelsSliderBeanInfo1;
    private rojerusan.RSTableMetro rSTableMetro1;
    public javax.swing.JTextField txt_Fecha_Devuelto;
    public javax.swing.JTextField txt_Fecha_Prestamo;
    public javax.swing.JTextField txt_Id_Reserva;
    public javax.swing.JTextField txt_N_Prestamo;
    // End of variables declaration//GEN-END:variables
}
