/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.ReservaJDBC;
import Datos.VistaDetalle_LibroJDBC;
import Domain.AtributosVistaDetalle_Libro;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres R
 */
public class VentanaReservarLibro_U extends javax.swing.JFrame {

    VentanaPrincipalUsuario vpu = new VentanaPrincipalUsuario();
    ReservaJDBC dbreserva = new ReservaJDBC();
    VistaDetalle_LibroJDBC dbvistadetalle = new VistaDetalle_LibroJDBC();

    /**
     * Creates new form VentanaReservarLibro_U
     */
    public VentanaReservarLibro_U() {
        initComponents();
        setLocationRelativeTo(null);
        txt_rId_Lector.setEditable(false);

    }

    public void SelectDetalle_Libro() {
        List<AtributosVistaDetalle_Libro> VistaDetalleLibro;
        VistaDetalleLibro = dbvistadetalle.select();
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (AtributosVistaDetalle_Libro in : VistaDetalleLibro) {
            tb.addRow(new Object[]{in.getId_Libro(), in.getTitulo(), in.getNombre()});
        }
    }

    public void SelectBusqueda_Libro() {
        String TituloLibro = txt_BuscarLibro.getText();
        List<AtributosVistaDetalle_Libro> VistaDetalleLibro = dbvistadetalle.SearchLibro(TituloLibro);
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (AtributosVistaDetalle_Libro in : VistaDetalleLibro) {
            tb.addRow(new Object[]{in.getId_Libro(), in.getTitulo(), in.getNombre()});
        }
    }

    public void LimpiarDatos() {
        DefaultTableModel tb = (DefaultTableModel) rSTableMetro1.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_GenerarReserva = new javax.swing.JButton();
        txt_rId_Lector = new javax.swing.JTextField();
        txt_rId_Libro = new javax.swing.JTextField();
        date_fecha_rprestamo = new com.toedter.calendar.JDateChooser();
        btn_MostrarLibros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        txt_BuscarLibro = new javax.swing.JTextField();
        bnt_BuscarLibro = new javax.swing.JButton();
        btn_Regresar = new javax.swing.JButton();
        label_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_cc = new javax.swing.JLabel();
        label_nombre1 = new javax.swing.JLabel();
        label_apellido = new javax.swing.JLabel();
        label_direccion = new javax.swing.JLabel();
        label_carrera = new javax.swing.JLabel();
        label_fechanac = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("RESERVAR UN LIBRO");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel3.setText("Id_Lector:");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel4.setText("Id_Libro:");

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel5.setText("Fecha_Prestamo:");

        btn_GenerarReserva.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btn_GenerarReserva.setText("Generar Reserva");
        btn_GenerarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarReservaActionPerformed(evt);
            }
        });

        txt_rId_Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rId_LibroActionPerformed(evt);
            }
        });

        date_fecha_rprestamo.setDateFormatString("yyyy-MM-dd");
        date_fecha_rprestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_fecha_rprestamoMouseClicked(evt);
            }
        });

        btn_MostrarLibros.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btn_MostrarLibros.setText("Mostrar Libros");
        btn_MostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_fecha_rprestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_rId_Lector)
                            .addComponent(txt_rId_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_GenerarReserva)
                        .addGap(18, 18, 18)
                        .addComponent(btn_MostrarLibros))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_rId_Lector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_rId_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(date_fecha_rprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GenerarReserva)
                    .addComponent(btn_MostrarLibros))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 410, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setText("Buscar Libro:");

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Libro", "Titulo", "Autor"
            }
        ));
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setColorSelBackgound(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        rSTableMetro1.setFuenteFilas(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        rSTableMetro1.setFuenteFilasSelect(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        rSTableMetro1.setFuenteHead(new java.awt.Font("Roboto Condensed", 1, 15)); // NOI18N
        rSTableMetro1.setRowHeight(30);
        jScrollPane1.setViewportView(rSTableMetro1);

        bnt_BuscarLibro.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        bnt_BuscarLibro.setText("Buscar");
        bnt_BuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_BuscarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bnt_BuscarLibro)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt_BuscarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 690, 290));

        btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Exit.png"))); // NOI18N
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        label_nombre.setText("jLabel7");
        jPanel1.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/FondoPrincipalUsuario.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        label_cc.setText("CC");
        jPanel1.add(label_cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        label_nombre1.setText("NOMBRE");
        jPanel1.add(label_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        label_apellido.setText("APELLIDO");
        jPanel1.add(label_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        label_direccion.setText("DIRECCION ");
        jPanel1.add(label_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        label_carrera.setText("CARRERA");
        jPanel1.add(label_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        label_fechanac.setText("FECHA_NAC");
        jPanel1.add(label_fechanac, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        label_telefono.setText("TELEFONO");
        jPanel1.add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        label_email.setText("EMAIL");
        jPanel1.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GenerarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarReservaActionPerformed
        int Id_Lector = Integer.parseInt(txt_rId_Lector.getText());
        int Id_Libro = Integer.parseInt(txt_rId_Libro.getText());
        String Fecha_Prestamo = ((JTextField) date_fecha_rprestamo.getDateEditor().getUiComponent()).getText();
        if (!"".equals(txt_rId_Lector.getText()) && !"".equals(txt_rId_Libro.getText()) && !"".equals(Fecha_Prestamo)) {
            dbreserva.insert(Id_Lector, Id_Libro, Fecha_Prestamo);
            if (dbreserva.correcto) {
                JOptionPane.showMessageDialog(null, "RESERVA GENERADA!");
            } else {
                JOptionPane.showMessageDialog(null, "HA OCURRIDO UN ERROR AL GENERAR LA RESERVA");
            }
        } else {
            JOptionPane.showMessageDialog(null, "LOS CAMPOS NO PUEDEN ESTAR VACIOS");
        }
    }//GEN-LAST:event_btn_GenerarReservaActionPerformed

    private void btn_MostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarLibrosActionPerformed
        LimpiarDatos();
        SelectDetalle_Libro();
    }//GEN-LAST:event_btn_MostrarLibrosActionPerformed

    private void bnt_BuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_BuscarLibroActionPerformed
        LimpiarDatos();
        SelectBusqueda_Libro();
    }//GEN-LAST:event_bnt_BuscarLibroActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        VentanaPrincipalUsuario ventana = new VentanaPrincipalUsuario();
        ventana.label_Id_Lector.setText(txt_rId_Lector.getText());
        ventana.label_name.setText(this.label_nombre.getText());
        ventana.label_cc.setText(this.label_cc.getText());
        ventana.label_nombre.setText(this.label_nombre1.getText());
        ventana.label_apellido.setText(this.label_apellido.getText());
        ventana.label_direccion.setText(this.label_direccion.getText());
        ventana.label_carrera.setText(this.label_carrera.getText());
        ventana.label_fechanac.setText(this.label_fechanac.getText());
        ventana.label_telefono.setText(this.label_telefono.getText());
        ventana.label_email.setText(this.label_email.getText());
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void txt_rId_LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rId_LibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rId_LibroActionPerformed

    private void date_fecha_rprestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_fecha_rprestamoMouseClicked

    }//GEN-LAST:event_date_fecha_rprestamoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReservarLibro_U.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReservarLibro_U.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReservarLibro_U.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReservarLibro_U.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReservarLibro_U().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_BuscarLibro;
    public javax.swing.JButton btn_GenerarReserva;
    public javax.swing.JButton btn_MostrarLibros;
    private javax.swing.JButton btn_Regresar;
    public com.toedter.calendar.JDateChooser date_fecha_rprestamo;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel label_apellido;
    public javax.swing.JLabel label_carrera;
    public javax.swing.JLabel label_cc;
    public javax.swing.JLabel label_direccion;
    public javax.swing.JLabel label_email;
    public javax.swing.JLabel label_fechanac;
    public javax.swing.JLabel label_nombre;
    public javax.swing.JLabel label_nombre1;
    public javax.swing.JLabel label_telefono;
    public rojerusan.RSTableMetro rSTableMetro1;
    private javax.swing.JTextField txt_BuscarLibro;
    public javax.swing.JTextField txt_rId_Lector;
    public javax.swing.JTextField txt_rId_Libro;
    // End of variables declaration//GEN-END:variables
}
